from __future__ import annotations
from pathlib import Path
import numpy as np
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from fractal_estimator import simple_random_walk, fbm_graph, levy_flight, box_count_base

GEN = Path(__file__).resolve().parent.parent / "generated"
SEED = 2026
N = 2 ** 16
SEEDS = 8
BASES = [1.5, 2.0, 2.5, 3.0]
EPS_LO, EPS_HI = 1.0 / 128, 1.0 / 4

CASES = [
    ("SRW $d{=}4$", lambda s: simple_random_walk(N, 4, np.random.default_rng(SEED + s))),
    ("fBm $H{=}0.5$", lambda s: fbm_graph(N, 0.5, np.random.default_rng(SEED + s))),
    (r"L\'evy $\alpha{=}1.4$", lambda s: levy_flight(N, 3, np.random.default_rng(SEED + s), 1.4)),
]


def dim_over_range(eps, counts):
    sel = (eps >= EPS_LO) & (eps <= EPS_HI)
    x = np.log(1.0 / eps[sel]); y = np.log(counts[sel])
    return float(np.polyfit(x, y, 1)[0])


table = {}
for name, gen in CASES:
    for b in BASES:
        nsc = int(np.ceil(np.log(256.0) / np.log(b))) + 1
        ds = [dim_over_range(*box_count_base(gen(s), b, nsc)) for s in range(SEEDS)]
        table[(name, b)] = float(np.mean(ds))
    print(name, {b: round(table[(name, b)], 3) for b in BASES})

spreads = [max(table[(n, b)] for b in BASES) - min(table[(n, b)] for b in BASES)
           for n, _ in CASES]
overall = max(spreads)

cols = "c" * len(CASES)
lines = [
    r"\begin{table}[t]", r"\centering",
    r"\caption{Robustness to non-dyadic grids. Box-counting graph dimension over the"
    r" same scale range $\epsilon\in[1/128,1/4]$ for grid bases $\epsilon=b^{-k}$,"
    f" at $N=2^{{{int(np.log2(N))}}}$ (mean over {SEEDS} seeds). Estimates shift by at"
    f" most ${overall:.2f}$ across bases, so the reported dimensions are not an"
    r" artifact of the dyadic ($b=2$) grid.}",
    r"\label{tab:nondyadic}", r"\small",
    r"\begin{tabular}{l" + cols + r"}", r"\toprule",
    "base $b$ & " + " & ".join(n for n, _ in CASES) + r"\\", r"\midrule",
]
for b in BASES:
    lines.append(f"${b}$ & " + " & ".join(f"${table[(n, b)]:.3f}$" for n, _ in CASES) + r"\\")
lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
(GEN / "results_nondyadic.tex").write_text("\n".join(lines), encoding="utf-8")

mac = ["% Auto-generated by analyze_nondyadic.py -- do not edit by hand.",
       f"\\newcommand{{\\nondyadicShift}}{{{overall:.2f}}}",
       f"\\newcommand{{\\nondyadicBases}}{{{', '.join(str(b) for b in BASES)}}}"]
(GEN / "macros_nondyadic.tex").write_text("\n".join(mac) + "\n", encoding="utf-8")
print(f"max shift across bases = {overall:.3f}; wrote results_nondyadic.tex, macros_nondyadic.tex")
